swagger: '2.0'
info:
  x-ibm-name: pokemon
  title: pokemon
  version: 1.0.0
schemes:
  - https
host: $(catalog.host)
basePath: /api
consumes:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
    description: ''
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          target-url: 'https://pokemons.mybluemix.net/api/pokemons/'
    catch: []
  gateway: datapower-gateway
paths:
  '/pokemon/{id}':
    get:
      responses:
        '200':
          description: 200 OK
    parameters:
      - name: id
        type: string
        required: true
        in: path
  /pokemon:
    get:
      responses:
        '200':
          description: 200 OK
    post:
      responses:
        '200':
          description: 200 OK
      parameters:
        - $ref: '#/parameters/Authorization'
definitions: {}
tags: []
produces:
  - application/json
parameters:
  Authorization:
    name: Authorization
    type: string
    required: false
    in: header
